steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=us-east4-docker.pkg.dev/daniel-346414/dockercloud/app-image', '.']

images: ['us-east4-docker.pkg.dev/daniel-346414/dockercloud/app-image']

options:
  logging: CLOUD_LOGGING_ONLY